plugins { id 'com.android.application' }

android {
    namespace 'cn.hui.gptpower'
    compileSdk 37
    buildToolsVersion '37.0.0'
    defaultConfig { applicationId 'cn.hui.gptpower'; minSdk 26; targetSdk 37; versionCode 1; versionName '0.3.0' }
    buildTypes { release { signingConfig signingConfigs.debug } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    packaging { resources { merges += 'META-INF/xposed/*' } }
}

dependencies { compileOnly 'io.github.libxposed:api:102.0.0' }
